name: focusguard_pro
description: A productivity SaaS mobile app focused on deep work and habit building.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Core / UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.5.1
  go_router: ^14.0.0
  shared_preferences: ^2.2.3
  
  # Data / Networking
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  http: ^1.2.1
  intl: ^0.20.2
  dio: ^5.9.2
  local_auth: ^2.3.0
  local_auth_android: ^1.0.51
  local_auth_darwin: ^1.6.0
  crypto: ^3.0.7
  flutter_windowmanager: ^0.2.0
  freerasp: ^7.4.0
  encrypt: ^5.0.3
  flutter_secure_storage: ^10.0.0
  sanitize_html: ^2.1.0
  package_info_plus: ^9.0.0
  uuid: ^4.5.3
  audioplayers: ^6.6.0
  device_calendar: ^3.9.0
  timezone: ^0.10.1
  drift: ^2.26.1
  connectivity_plus: ^7.0.0
  hive_flutter: ^1.1.0
  path: ^1.9.0
  path_provider: ^2.1.5
  sqlite3_flutter_libs: ^0.5.41
  flutter_animate: ^4.5.2
  shimmer: ^3.0.0
  flutter_local_notifications: ^19.5.0
  share_plus: ^12.0.1

  hive: any
  fl_chart: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  integration_test:
    sdk: flutter
  build_runner: ^2.4.9
  # Mocks/Coverage tools commonly used
  mockito: ^5.4.4
  coverage: ^1.8.0
  drift_dev: any
  riverpod_generator: any
  riverpod_annotation: any

flutter:
  uses-material-design: true

  # assets:
  #   - assets/images/
  #   - assets/animations/
  
    #   - family: Inter
    #     fonts:
    #       - asset: assets/fonts/Inter-Regular.ttf
    #       - asset: assets/fonts/Inter-SemiBold.ttf
dependency_overrides:
  source_gen: any
