export declare const Topics: {
    readonly USER_CREATED: "user.created";
    readonly USER_DELETED: "user.deleted";
    readonly SESSION_COMPLETED: "session.completed";
    readonly USAGE_SYNCED: "usage.synced";
    readonly ACHIEVEMENT_UNLOCKED: "achievement.unlocked";
    readonly SUBSCRIPTION_CHANGED: "subscription.changed";
    readonly CHALLENGE_COMPLETED: "challenge.completed";
    readonly REPORT_READY: "report.ready";
    readonly STREAK_MILESTONE: "streak.milestone";
    readonly LEVEL_UP: "level.up";
};
export declare const Queues: {
    readonly SCORE_CALCULATION: "score-calculation";
    readonly NOTIFICATIONS: "notifications";
    readonly LEADERBOARD_UPDATE: "leaderboard-update";
    readonly REPORT_GENERATION: "report-generation";
    readonly ACHIEVEMENT_CHECK: "achievement-check";
    readonly BIGQUERY_SYNC: "bigquery-sync";
    readonly EMAIL_DELIVERY: "email-delivery";
    readonly AI_INSIGHTS: "ai-insights";
};
export declare const FeatureFlags: {
    readonly AI_COACHING_ENABLED: true;
    readonly FOCUS_SPACES_ENABLED: true;
    readonly LIVE_ACTIVITIES_ENABLED: false;
    readonly WATCH_APP_ENABLED: false;
    readonly REFERRAL_SYSTEM_ENABLED: true;
    readonly STRICT_MODE_ENABLED: true;
    readonly CHALLENGES_ENABLED: true;
};
export declare const TierLimits: {
    readonly free: {
        readonly blockedApps: 3;
        readonly statsDays: 7;
        readonly goals: 3;
        readonly habits: 3;
        readonly accountabilityPartners: 0;
        readonly aiMonthlyMessages: 0;
        readonly fullAnalytics: false;
        readonly achievements: false;
        readonly leaderboard: false;
        readonly challenges: false;
        readonly exportReports: false;
        readonly focusModes: false;
        readonly focusSpaces: false;
        readonly ambientSounds: false;
        readonly aiCoaching: false;
        readonly bedtimeMode: false;
        readonly strictModeBiometric: false;
    };
    readonly basic: {
        readonly blockedApps: 10;
        readonly statsDays: 30;
        readonly goals: 10;
        readonly habits: 5;
        readonly accountabilityPartners: 0;
        readonly aiMonthlyMessages: 0;
        readonly fullAnalytics: false;
        readonly achievements: false;
        readonly leaderboard: false;
        readonly challenges: false;
        readonly exportReports: false;
        readonly focusModes: false;
        readonly focusSpaces: false;
        readonly ambientSounds: false;
        readonly aiCoaching: false;
        readonly bedtimeMode: false;
        readonly strictModeBiometric: false;
    };
    readonly pro: {
        readonly blockedApps: number;
        readonly statsDays: 365;
        readonly goals: number;
        readonly habits: number;
        readonly accountabilityPartners: 1;
        readonly aiMonthlyMessages: 10;
        readonly fullAnalytics: true;
        readonly achievements: true;
        readonly leaderboard: true;
        readonly challenges: true;
        readonly exportReports: true;
        readonly focusModes: true;
        readonly focusSpaces: true;
        readonly ambientSounds: true;
        readonly aiCoaching: true;
        readonly bedtimeMode: true;
        readonly strictModeBiometric: false;
    };
    readonly elite: {
        readonly blockedApps: number;
        readonly statsDays: 365;
        readonly goals: number;
        readonly habits: number;
        readonly accountabilityPartners: number;
        readonly aiMonthlyMessages: 500;
        readonly fullAnalytics: true;
        readonly achievements: true;
        readonly leaderboard: true;
        readonly challenges: true;
        readonly exportReports: true;
        readonly focusModes: true;
        readonly focusSpaces: true;
        readonly ambientSounds: true;
        readonly aiCoaching: true;
        readonly bedtimeMode: true;
        readonly strictModeBiometric: true;
    };
    readonly lifetime: {
        readonly blockedApps: number;
        readonly statsDays: 365;
        readonly goals: number;
        readonly habits: number;
        readonly accountabilityPartners: number;
        readonly aiMonthlyMessages: 500;
        readonly fullAnalytics: true;
        readonly achievements: true;
        readonly leaderboard: true;
        readonly challenges: true;
        readonly exportReports: true;
        readonly focusModes: true;
        readonly focusSpaces: true;
        readonly ambientSounds: true;
        readonly aiCoaching: true;
        readonly bedtimeMode: true;
        readonly strictModeBiometric: true;
    };
};
export type TierName = keyof typeof TierLimits;
//# sourceMappingURL=feature.flags.d.ts.map