"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TierLimits = exports.FeatureFlags = exports.Queues = exports.Topics = void 0;
// Pub/Sub topics
exports.Topics = {
    USER_CREATED: 'user.created',
    USER_DELETED: 'user.deleted',
    SESSION_COMPLETED: 'session.completed',
    USAGE_SYNCED: 'usage.synced',
    ACHIEVEMENT_UNLOCKED: 'achievement.unlocked',
    SUBSCRIPTION_CHANGED: 'subscription.changed',
    CHALLENGE_COMPLETED: 'challenge.completed',
    REPORT_READY: 'report.ready',
    STREAK_MILESTONE: 'streak.milestone',
    LEVEL_UP: 'level.up',
};
// Cloud Task queues
exports.Queues = {
    SCORE_CALCULATION: 'score-calculation',
    NOTIFICATIONS: 'notifications',
    LEADERBOARD_UPDATE: 'leaderboard-update',
    REPORT_GENERATION: 'report-generation',
    ACHIEVEMENT_CHECK: 'achievement-check',
    BIGQUERY_SYNC: 'bigquery-sync',
    EMAIL_DELIVERY: 'email-delivery',
    AI_INSIGHTS: 'ai-insights',
};
// Feature flags
exports.FeatureFlags = {
    AI_COACHING_ENABLED: true,
    FOCUS_SPACES_ENABLED: true,
    LIVE_ACTIVITIES_ENABLED: false,
    WATCH_APP_ENABLED: false,
    REFERRAL_SYSTEM_ENABLED: true,
    STRICT_MODE_ENABLED: true,
    CHALLENGES_ENABLED: true,
};
// Subscription tier feature limits
exports.TierLimits = {
    free: {
        blockedApps: 3,
        statsDays: 7,
        goals: 3,
        habits: 3,
        accountabilityPartners: 0,
        aiMonthlyMessages: 0,
        fullAnalytics: false,
        achievements: false,
        leaderboard: false,
        challenges: false,
        exportReports: false,
        focusModes: false,
        focusSpaces: false,
        ambientSounds: false,
        aiCoaching: false,
        bedtimeMode: false,
        strictModeBiometric: false,
    },
    basic: {
        blockedApps: 10,
        statsDays: 30,
        goals: 10,
        habits: 5,
        accountabilityPartners: 0,
        aiMonthlyMessages: 0,
        fullAnalytics: false,
        achievements: false,
        leaderboard: false,
        challenges: false,
        exportReports: false,
        focusModes: false,
        focusSpaces: false,
        ambientSounds: false,
        aiCoaching: false,
        bedtimeMode: false,
        strictModeBiometric: false,
    },
    pro: {
        blockedApps: Infinity,
        statsDays: 365,
        goals: Infinity,
        habits: Infinity,
        accountabilityPartners: 1,
        aiMonthlyMessages: 10,
        fullAnalytics: true,
        achievements: true,
        leaderboard: true,
        challenges: true,
        exportReports: true,
        focusModes: true,
        focusSpaces: true,
        ambientSounds: true,
        aiCoaching: true,
        bedtimeMode: true,
        strictModeBiometric: false,
    },
    elite: {
        blockedApps: Infinity,
        statsDays: 365,
        goals: Infinity,
        habits: Infinity,
        accountabilityPartners: Infinity,
        aiMonthlyMessages: 500,
        fullAnalytics: true,
        achievements: true,
        leaderboard: true,
        challenges: true,
        exportReports: true,
        focusModes: true,
        focusSpaces: true,
        ambientSounds: true,
        aiCoaching: true,
        bedtimeMode: true,
        strictModeBiometric: true,
    },
    lifetime: {
        blockedApps: Infinity,
        statsDays: 365,
        goals: Infinity,
        habits: Infinity,
        accountabilityPartners: Infinity,
        aiMonthlyMessages: 500,
        fullAnalytics: true,
        achievements: true,
        leaderboard: true,
        challenges: true,
        exportReports: true,
        focusModes: true,
        focusSpaces: true,
        ambientSounds: true,
        aiCoaching: true,
        bedtimeMode: true,
        strictModeBiometric: true,
    },
};
//# sourceMappingURL=feature.flags.js.map