import * as functions from 'firebase-functions';
export { onUserCreated, onUserDeleted, beforeSignIn, beforeCreate } from './auth/auth.triggers';
export { onUserDocumentUpdate } from './users/users.triggers';
export { createSession, completeSession, getSessionAnalytics } from './sessions/sessions.service';
export { syncDailyUsage, getUsageAnalytics } from './usage/usage.service';
export { setGoal, evaluateGoalsAtDayEnd } from './goals/goals.service';
export { createHabit, trackHabit, calculateHabitStreaks } from './habits/habits.service';
export { getAICoaching } from './ai/ai.service';
export { revenuecatWebhook, checkEntitlements } from './subscriptions/subscriptions.service';
export { getLeaderboard, rebuildLeaderboard } from './leaderboard/leaderboard.service';
export { sendStreakReminders } from './notifications/notifications.service';
export { createBlockingSchedule, updateBlockingSchedule, createFocusMode, getActiveBlocks, logOverrideAttempt, } from './blocking/blocking.service';
export { joinChallenge, withdrawChallenge, getChallengeDetails, updateChallengeProgress, } from './challenges/challenges.service';
export { invitePartner, acceptPartner, sendNudge, createAccountabilityGroup, updateAccountabilityStats, } from './accountability/accountability.service';
export { createReferralLink, processReferral, processReferralRewards, } from './referrals/referrals.service';
export { generateWeeklyReport, generateMonthlyReport } from './reports/reports.service';
export { syncDailyStatsToBigQuery, aggregateWeeklyAnalytics, cleanupOldNotifications, } from './analytics/analytics.service';
export { generateTOTPSecret, verifyTOTPToken, sendSMSCode, verifySMSCode, verifyBackupCode, disableMFA, } from './auth/mfa.service';
export { onSessionCompleted as pubsubSessionCompleted, onUsageSynced as pubsubUsageSynced, onAchievementUnlocked as pubsubAchievementUnlocked, onSubscriptionChanged as pubsubSubscriptionChanged, onReportReady as pubsubReportReady, onLevelUp as pubsubLevelUp, } from './pubsub/pubsub.handlers';
export { stripeWebhook, sendgridWebhook } from './webhooks/webhooks.handlers';
export declare const api: functions.HttpsFunction;
//# sourceMappingURL=index.d.ts.map