import { AchievementDefinitionDocument } from '../shared/types/firestore.types';

// ─── 60 Achievement Definitions ───

export const ACHIEVEMENT_DEFINITIONS: Omit<AchievementDefinitionDocument, 'isActive' | 'order'>[] =
  [
    // === FOCUS (15) ===
    {
      achievementId: 'first_focus',
      name: 'First Steps',
      description: 'Complete your first focus session',
      category: 'focus',
      rarity: 'common',
      icon: '🎯',
      xpReward: 100,
      condition: {
        metric: 'sessions_completed',
        operator: 'gte',
        value: 1,
        timeWindow: 'all_time',
      },
      unlockMessage: 'Your focus journey begins! 🎯',
    },
    {
      achievementId: 'pomodoro_5',
      name: 'Getting Started',
      description: 'Complete 5 focus sessions',
      category: 'focus',
      rarity: 'common',
      icon: '⏱️',
      xpReward: 150,
      condition: {
        metric: 'sessions_completed',
        operator: 'gte',
        value: 5,
        timeWindow: 'all_time',
      },
      unlockMessage: "5 sessions done! You're building a habit!",
    },
    {
      achievementId: 'pomodoro_25',
      name: 'Focus Warrior',
      description: 'Complete 25 focus sessions',
      category: 'focus',
      rarity: 'rare',
      icon: '⚔️',
      xpReward: 300,
      condition: {
        metric: 'sessions_completed',
        operator: 'gte',
        value: 25,
        timeWindow: 'all_time',
      },
      unlockMessage: "25 sessions! You're a Focus Warrior!",
    },
    {
      achievementId: 'pomodoro_100',
      name: 'Focus Master',
      description: 'Complete 100 focus sessions',
      category: 'focus',
      rarity: 'epic',
      icon: '🏆',
      xpReward: 750,
      condition: {
        metric: 'sessions_completed',
        operator: 'gte',
        value: 100,
        timeWindow: 'all_time',
      },
      unlockMessage: "100 sessions! You've mastered focus!",
    },
    {
      achievementId: 'pomodoro_500',
      name: 'Focus Legend',
      description: 'Complete 500 focus sessions',
      category: 'focus',
      rarity: 'legendary',
      icon: '👑',
      xpReward: 2000,
      condition: {
        metric: 'sessions_completed',
        operator: 'gte',
        value: 500,
        timeWindow: 'all_time',
      },
      unlockMessage: "500 sessions! You're legendary!",
    },
    {
      achievementId: 'deep_work_1',
      name: 'Deep Diver',
      description: 'Complete a 2+ hour focus session',
      category: 'focus',
      rarity: 'common',
      icon: '🤿',
      xpReward: 200,
      condition: {
        metric: 'longest_session_minutes',
        operator: 'gte',
        value: 120,
        timeWindow: null,
      },
      unlockMessage: '2+ hours of deep work! Impressive!',
    },
    {
      achievementId: 'deep_work_10',
      name: 'Deep Work Pro',
      description: 'Complete 10 sessions of 2+ hours',
      category: 'focus',
      rarity: 'rare',
      icon: '🧠',
      xpReward: 500,
      condition: {
        metric: 'deep_sessions_count',
        operator: 'gte',
        value: 10,
        timeWindow: 'all_time',
      },
      unlockMessage: "10 deep work sessions! You're a pro!",
    },
    {
      achievementId: 'marathon_session',
      name: 'Marathon Runner',
      description: 'Complete a 4+ hour focus session',
      category: 'focus',
      rarity: 'epic',
      icon: '🏃',
      xpReward: 1000,
      condition: {
        metric: 'longest_session_minutes',
        operator: 'gte',
        value: 240,
        timeWindow: null,
      },
      unlockMessage: "4+ hours! That's a marathon of focus!",
    },
    {
      achievementId: 'focus_hours_10',
      name: '10 Hour Club',
      description: 'Accumulate 10 total focus hours',
      category: 'focus',
      rarity: 'common',
      icon: '⏰',
      xpReward: 200,
      condition: {
        metric: 'total_focus_minutes',
        operator: 'gte',
        value: 600,
        timeWindow: 'all_time',
      },
      unlockMessage: '10 hours of focused work!',
    },
    {
      achievementId: 'focus_hours_100',
      name: 'Century Focus',
      description: 'Accumulate 100 total focus hours',
      category: 'focus',
      rarity: 'rare',
      icon: '💯',
      xpReward: 500,
      condition: {
        metric: 'total_focus_minutes',
        operator: 'gte',
        value: 6000,
        timeWindow: 'all_time',
      },
      unlockMessage: '100 hours! A century of focus!',
    },
    {
      achievementId: 'focus_hours_500',
      name: 'Focus Titan',
      description: 'Accumulate 500 total focus hours',
      category: 'focus',
      rarity: 'epic',
      icon: '🦾',
      xpReward: 1500,
      condition: {
        metric: 'total_focus_minutes',
        operator: 'gte',
        value: 30000,
        timeWindow: 'all_time',
      },
      unlockMessage: '500 hours! Titan-level focus!',
    },
    {
      achievementId: 'focus_hours_1000',
      name: 'Focus Immortal',
      description: 'Accumulate 1000 total focus hours',
      category: 'focus',
      rarity: 'legendary',
      icon: '🌟',
      xpReward: 5000,
      condition: {
        metric: 'total_focus_minutes',
        operator: 'gte',
        value: 60000,
        timeWindow: 'all_time',
      },
      unlockMessage: "1000 hours! You're immortal!",
    },
    {
      achievementId: 'early_bird_5',
      name: 'Early Bird',
      description: 'Start 5 sessions before 8am',
      category: 'focus',
      rarity: 'rare',
      icon: '🐦',
      xpReward: 400,
      condition: { metric: 'early_sessions', operator: 'gte', value: 5, timeWindow: 'all_time' },
      unlockMessage: 'Early bird gets the focus!',
    },
    {
      achievementId: 'night_owl_5',
      name: 'Night Owl',
      description: 'Complete 5 sessions after 9pm',
      category: 'focus',
      rarity: 'rare',
      icon: '🦉',
      xpReward: 400,
      condition: { metric: 'late_sessions', operator: 'gte', value: 5, timeWindow: 'all_time' },
      unlockMessage: 'Night owl productivity!',
    },
    {
      achievementId: 'perfect_session',
      name: 'Zen Focus',
      description: 'Complete a session with 0 distractions and 100% completion',
      category: 'focus',
      rarity: 'epic',
      icon: '🧘',
      xpReward: 600,
      condition: { metric: 'perfect_sessions', operator: 'gte', value: 1, timeWindow: null },
      unlockMessage: 'Pure, undistracted focus!',
    },

    // === SOCIAL MEDIA (12) ===
    {
      achievementId: 'first_block',
      name: 'First Block',
      description: 'Block your first distracting app',
      category: 'social',
      rarity: 'common',
      icon: '🚫',
      xpReward: 50,
      condition: { metric: 'apps_blocked', operator: 'gte', value: 1, timeWindow: 'all_time' },
      unlockMessage: 'First app blocked! 🚫',
    },
    {
      achievementId: 'blocked_10',
      name: 'Block Party',
      description: 'Block 10 distraction attempts',
      category: 'social',
      rarity: 'common',
      icon: '🛡️',
      xpReward: 100,
      condition: { metric: 'apps_blocked', operator: 'gte', value: 10, timeWindow: 'all_time' },
      unlockMessage: '10 blocks! Stay strong!',
    },
    {
      achievementId: 'blocked_100',
      name: 'Distraction Shield',
      description: 'Block 100 distraction attempts',
      category: 'social',
      rarity: 'rare',
      icon: '🔰',
      xpReward: 300,
      condition: { metric: 'apps_blocked', operator: 'gte', value: 100, timeWindow: 'all_time' },
      unlockMessage: '100 blocks! Your shield is strong!',
    },
    {
      achievementId: 'blocked_1000',
      name: 'Fortress Mind',
      description: 'Block 1000 distraction attempts',
      category: 'social',
      rarity: 'epic',
      icon: '🏰',
      xpReward: 1000,
      condition: { metric: 'apps_blocked', operator: 'gte', value: 1000, timeWindow: 'all_time' },
      unlockMessage: 'Your mind is a fortress!',
    },
    {
      achievementId: 'detox_day_1',
      name: 'Digital Detox',
      description: 'Complete a social media free day',
      category: 'social',
      rarity: 'rare',
      icon: '🌿',
      xpReward: 500,
      condition: { metric: 'social_free_days', operator: 'gte', value: 1, timeWindow: null },
      unlockMessage: 'A whole day without social media!',
    },
    {
      achievementId: 'detox_week',
      name: 'Detox Week',
      description: '7 consecutive social media free days',
      category: 'social',
      rarity: 'epic',
      icon: '🌱',
      xpReward: 1500,
      condition: { metric: 'social_free_streak', operator: 'gte', value: 7, timeWindow: null },
      unlockMessage: 'A WEEK without social media! 🌱',
    },
    {
      achievementId: 'detox_month',
      name: 'Detox Champion',
      description: '30 consecutive social media free days',
      category: 'social',
      rarity: 'legendary',
      icon: '🏆',
      xpReward: 5000,
      condition: { metric: 'social_free_streak', operator: 'gte', value: 30, timeWindow: null },
      unlockMessage: 'A MONTH social media free! Legend!',
    },
    {
      achievementId: 'reel_resister_100',
      name: 'Reel Resister',
      description: 'Resist 100+ short-form video attempts',
      category: 'social',
      rarity: 'rare',
      icon: '📱',
      xpReward: 400,
      condition: { metric: 'reels_blocked', operator: 'gte', value: 100, timeWindow: 'all_time' },
      unlockMessage: 'Bye bye reels! 📱',
    },
    {
      achievementId: 'goal_under_50',
      name: 'Half Measures',
      description: 'Stay 50% below social media goal for 7 days',
      category: 'social',
      rarity: 'rare',
      icon: '📉',
      xpReward: 400,
      condition: { metric: 'goal_under_50_days', operator: 'gte', value: 7, timeWindow: null },
      unlockMessage: 'Using only half your limit! ',
    },
    {
      achievementId: 'social_reducer_25',
      name: 'Social Reducer',
      description: '25% reduction week-over-week',
      category: 'social',
      rarity: 'rare',
      icon: '📊',
      xpReward: 350,
      condition: {
        metric: 'social_reduction_pct',
        operator: 'gte',
        value: 25,
        timeWindow: 'weekly',
      },
      unlockMessage: '25% less social media this week!',
    },
    {
      achievementId: 'social_reducer_50',
      name: 'Social Slasher',
      description: '50% reduction month-over-month',
      category: 'social',
      rarity: 'epic',
      icon: '⚡',
      xpReward: 800,
      condition: {
        metric: 'social_reduction_pct',
        operator: 'gte',
        value: 50,
        timeWindow: 'monthly',
      },
      unlockMessage: 'Cut social media in HALF!',
    },
    {
      achievementId: 'digital_minimalist',
      name: 'Digital Minimalist',
      description: 'Under 1 hour total social media for entire month',
      category: 'social',
      rarity: 'legendary',
      icon: '🎋',
      xpReward: 3000,
      condition: {
        metric: 'monthly_social_minutes',
        operator: 'lte',
        value: 60,
        timeWindow: 'monthly',
      },
      unlockMessage: 'True digital minimalist!',
    },

    // === STREAK (10) ===
    {
      achievementId: 'streak_3',
      name: 'Three-peat',
      description: '3-day streak',
      category: 'streak',
      rarity: 'common',
      icon: '🔥',
      xpReward: 150,
      condition: { metric: 'current_streak', operator: 'gte', value: 3, timeWindow: null },
      unlockMessage: '3-day streak! Keep it going! 🔥',
    },
    {
      achievementId: 'streak_7',
      name: 'Week Warrior',
      description: '7-day streak',
      category: 'streak',
      rarity: 'common',
      icon: '🗓️',
      xpReward: 300,
      condition: { metric: 'current_streak', operator: 'gte', value: 7, timeWindow: null },
      unlockMessage: 'A full week! 🗓️',
    },
    {
      achievementId: 'streak_14',
      name: 'Fortnight Focus',
      description: '14-day streak',
      category: 'streak',
      rarity: 'rare',
      icon: '💪',
      xpReward: 600,
      condition: { metric: 'current_streak', operator: 'gte', value: 14, timeWindow: null },
      unlockMessage: '14 days! Unstoppable! 💪',
    },
    {
      achievementId: 'streak_30',
      name: 'Monthly Master',
      description: '30-day streak',
      category: 'streak',
      rarity: 'rare',
      icon: '🏅',
      xpReward: 1000,
      condition: { metric: 'current_streak', operator: 'gte', value: 30, timeWindow: null },
      unlockMessage: '30-day streak! 🏅',
    },
    {
      achievementId: 'streak_60',
      name: 'Two Month Titan',
      description: '60-day streak',
      category: 'streak',
      rarity: 'epic',
      icon: '💎',
      xpReward: 2000,
      condition: { metric: 'current_streak', operator: 'gte', value: 60, timeWindow: null },
      unlockMessage: '60 days! Diamond streak! 💎',
    },
    {
      achievementId: 'streak_90',
      name: 'Quarter King',
      description: '90-day streak',
      category: 'streak',
      rarity: 'epic',
      icon: '🦁',
      xpReward: 3000,
      condition: { metric: 'current_streak', operator: 'gte', value: 90, timeWindow: null },
      unlockMessage: '90-day streak! 🦁',
    },
    {
      achievementId: 'streak_180',
      name: 'Half Year Hero',
      description: '180-day streak',
      category: 'streak',
      rarity: 'legendary',
      icon: '🌟',
      xpReward: 5000,
      condition: { metric: 'current_streak', operator: 'gte', value: 180, timeWindow: null },
      unlockMessage: 'HALF A YEAR! 🌟',
    },
    {
      achievementId: 'streak_365',
      name: 'Year of Focus',
      description: '365-day streak',
      category: 'streak',
      rarity: 'legendary',
      icon: '🏆',
      xpReward: 10000,
      condition: { metric: 'current_streak', operator: 'gte', value: 365, timeWindow: null },
      unlockMessage: 'A FULL YEAR! You are extraordinary!',
    },
    {
      achievementId: 'streak_comeback',
      name: 'Comeback Kid',
      description: 'Rebuild streak to 7 after breaking it',
      category: 'streak',
      rarity: 'rare',
      icon: '🔄',
      xpReward: 400,
      condition: { metric: 'comeback_streak', operator: 'gte', value: 7, timeWindow: null },
      unlockMessage: 'Comeback complete! 🔄',
    },
    {
      achievementId: 'unbreakable',
      name: 'Unbreakable',
      description: '30-day streak with 0 skips',
      category: 'streak',
      rarity: 'epic',
      icon: '🛡️',
      xpReward: 1500,
      condition: { metric: 'no_skip_streak', operator: 'gte', value: 30, timeWindow: null },
      unlockMessage: 'Unbreakable! No skips needed!',
    },

    // === HABIT (10) ===
    {
      achievementId: 'habit_first',
      name: 'Habit Builder',
      description: 'Create your first habit',
      category: 'habit',
      rarity: 'common',
      icon: '📝',
      xpReward: 100,
      condition: { metric: 'habits_created', operator: 'gte', value: 1, timeWindow: 'all_time' },
      unlockMessage: 'Your first habit! Great start!',
    },
    {
      achievementId: 'habit_completed_7',
      name: 'Seven Day Habit',
      description: 'Complete same habit 7 days in a row',
      category: 'habit',
      rarity: 'common',
      icon: '✅',
      xpReward: 200,
      condition: { metric: 'habit_streak', operator: 'gte', value: 7, timeWindow: null },
      unlockMessage: '7-day habit streak!',
    },
    {
      achievementId: 'habit_streak_21',
      name: 'Habit Formed',
      description: "21-day habit streak — science says it's a habit now!",
      category: 'habit',
      rarity: 'rare',
      icon: '🧬',
      xpReward: 500,
      condition: { metric: 'habit_streak', operator: 'gte', value: 21, timeWindow: null },
      unlockMessage: "It's officially a habit! 🧬",
    },
    {
      achievementId: 'habit_streak_90',
      name: 'Habit Master',
      description: '90-day habit streak',
      category: 'habit',
      rarity: 'epic',
      icon: '🎖️',
      xpReward: 1500,
      condition: { metric: 'habit_streak', operator: 'gte', value: 90, timeWindow: null },
      unlockMessage: "90-day habit — it's who you are!",
    },
    {
      achievementId: 'habit_stack_5',
      name: 'Stack Master',
      description: 'Complete 5 habits in the same day',
      category: 'habit',
      rarity: 'rare',
      icon: '📚',
      xpReward: 400,
      condition: {
        metric: 'daily_habits_completed',
        operator: 'gte',
        value: 5,
        timeWindow: 'daily',
      },
      unlockMessage: '5 habits in one day!',
    },
    {
      achievementId: 'habit_all_month',
      name: 'Perfect Month',
      description: 'Complete all habits every day for a month',
      category: 'habit',
      rarity: 'legendary',
      icon: '🌙',
      xpReward: 3000,
      condition: { metric: 'all_habits_month', operator: 'gte', value: 30, timeWindow: 'monthly' },
      unlockMessage: 'Perfect habit month! 🌙',
    },
    {
      achievementId: 'morning_champion_30',
      name: 'Morning Champion',
      description: 'No phone first hour for 30 days',
      category: 'habit',
      rarity: 'epic',
      icon: '🌅',
      xpReward: 1000,
      condition: {
        metric: 'morning_free_days',
        operator: 'gte',
        value: 30,
        timeWindow: 'all_time',
      },
      unlockMessage: 'Morning champion! 30 days screen-free start!',
    },
    {
      achievementId: 'habit_collector_10',
      name: 'Habit Collector',
      description: 'Create 10 different habits',
      category: 'habit',
      rarity: 'rare',
      icon: '🗂️',
      xpReward: 400,
      condition: { metric: 'habits_created', operator: 'gte', value: 10, timeWindow: 'all_time' },
      unlockMessage: "10 habits! You're a collector!",
    },
    {
      achievementId: 'template_master',
      name: 'Template Master',
      description: 'Use 5 habit templates',
      category: 'habit',
      rarity: 'common',
      icon: '📋',
      xpReward: 200,
      condition: { metric: 'templates_used', operator: 'gte', value: 5, timeWindow: 'all_time' },
      unlockMessage: 'Template pro!',
    },
    {
      achievementId: 'habit_perfect_week',
      name: 'Perfect Week',
      description: 'All habits completed every day for a week',
      category: 'habit',
      rarity: 'rare',
      icon: '🌈',
      xpReward: 500,
      condition: { metric: 'all_habits_week', operator: 'gte', value: 7, timeWindow: 'weekly' },
      unlockMessage: 'Perfect habit week! 🌈',
    },

    // === SOCIAL/FEATURE (8) ===
    {
      achievementId: 'accountability_day_1',
      name: 'Accountability Buddy',
      description: 'First day with an accountability partner',
      category: 'social_feature',
      rarity: 'common',
      icon: '🤝',
      xpReward: 150,
      condition: { metric: 'partner_days', operator: 'gte', value: 1, timeWindow: null },
      unlockMessage: 'Accountability buddy activated! 🤝',
    },
    {
      achievementId: 'accountability_30',
      name: 'Power Pair',
      description: '30 days with accountability partner',
      category: 'social_feature',
      rarity: 'rare',
      icon: '💪',
      xpReward: 500,
      condition: { metric: 'partner_days', operator: 'gte', value: 30, timeWindow: 'all_time' },
      unlockMessage: '30 days of accountability!',
    },
    {
      achievementId: 'challenge_first',
      name: 'Challenger',
      description: 'Complete your first challenge',
      category: 'social_feature',
      rarity: 'common',
      icon: '🏁',
      xpReward: 200,
      condition: {
        metric: 'challenges_completed',
        operator: 'gte',
        value: 1,
        timeWindow: 'all_time',
      },
      unlockMessage: 'First challenge completed! 🏁',
    },
    {
      achievementId: 'challenge_5',
      name: 'Challenge Champion',
      description: 'Complete 5 challenges',
      category: 'social_feature',
      rarity: 'rare',
      icon: '🥇',
      xpReward: 600,
      condition: {
        metric: 'challenges_completed',
        operator: 'gte',
        value: 5,
        timeWindow: 'all_time',
      },
      unlockMessage: '5 challenges! Champion!',
    },
    {
      achievementId: 'leaderboard_top100',
      name: 'Top 100',
      description: 'Reach global top 100',
      category: 'social_feature',
      rarity: 'epic',
      icon: '📊',
      xpReward: 1000,
      condition: { metric: 'leaderboard_rank', operator: 'lte', value: 100, timeWindow: null },
      unlockMessage: 'Global Top 100! 📊',
    },
    {
      achievementId: 'leaderboard_top10',
      name: 'Top 10',
      description: 'Reach global top 10',
      category: 'social_feature',
      rarity: 'legendary',
      icon: '👑',
      xpReward: 5000,
      condition: { metric: 'leaderboard_rank', operator: 'lte', value: 10, timeWindow: null },
      unlockMessage: 'GLOBAL TOP 10! 👑',
    },
    {
      achievementId: 'referral_3',
      name: 'Recruiter',
      description: 'Refer 3 friends',
      category: 'social_feature',
      rarity: 'rare',
      icon: '📨',
      xpReward: 500,
      condition: { metric: 'referral_count', operator: 'gte', value: 3, timeWindow: 'all_time' },
      unlockMessage: '3 friends joined! Ambassador!',
    },
    {
      achievementId: 'community_leader',
      name: 'Community Leader',
      description: 'Host a Focus Space room',
      category: 'social_feature',
      rarity: 'common',
      icon: '🏠',
      xpReward: 200,
      condition: {
        metric: 'focus_spaces_hosted',
        operator: 'gte',
        value: 1,
        timeWindow: 'all_time',
      },
      unlockMessage: "You're a Focus Space leader!",
    },

    // === SPECIAL (5) ===
    {
      achievementId: 'perfect_week',
      name: 'Perfect Week',
      description: 'All goals met every day for 7 days',
      category: 'special',
      rarity: 'epic',
      icon: '⭐',
      xpReward: 1000,
      condition: { metric: 'all_goals_met_streak', operator: 'gte', value: 7, timeWindow: null },
      unlockMessage: 'PERFECT WEEK! Every goal met!',
    },
    {
      achievementId: 'perfect_month',
      name: 'Perfect Month',
      description: 'All goals met every day for 30 days',
      category: 'special',
      rarity: 'legendary',
      icon: '🌟',
      xpReward: 5000,
      condition: { metric: 'all_goals_met_streak', operator: 'gte', value: 30, timeWindow: null },
      unlockMessage: "PERFECT MONTH! You're extraordinary!",
    },
    {
      achievementId: 'score_100',
      name: 'Perfect Score',
      description: 'Achieve 100/100 productivity score',
      category: 'special',
      rarity: 'epic',
      icon: '💯',
      xpReward: 1000,
      condition: { metric: 'daily_score', operator: 'eq', value: 100, timeWindow: 'daily' },
      unlockMessage: 'PERFECT 100! Flawless day!',
    },
    {
      achievementId: 'og_user',
      name: 'OG User',
      description: 'Early adopter — joined in first 6 months',
      category: 'special',
      rarity: 'legendary',
      icon: '🏴',
      xpReward: 2000,
      condition: { metric: 'join_date', operator: 'special', value: 0, timeWindow: null },
      unlockMessage: 'OG User! You were here first!',
    },
    {
      achievementId: 'level_50',
      name: 'Max Level',
      description: 'Reach Level 50',
      category: 'special',
      rarity: 'legendary',
      icon: '🎮',
      xpReward: 10000,
      condition: { metric: 'user_level', operator: 'gte', value: 50, timeWindow: null },
      unlockMessage: 'LEVEL 50! Maximum achieved!',
    },
  ];
